---
- hosts: 127.0.0.1
  become: yes
  become_user: codio
  tasks:

    - name: Install jupyter-collaboration
      pip:
        name: jupyter-collaboration
        executable: pip3
        state: present

    - name: Remove jupyter-server-ydoc
      pip:
        name: jupyter-server-ydoc
        executable: pip3
        state: absent

    - name: Install jupyter-server-ydoc-codio
      pip:
        extra_args: -i https://test.pypi.org/simple/
        name: jupyter-server-ydoc-codio
        executable: pip3
        state: present

    - name: "Restart Jupyter"
      become: yes
      systemd:
        state: restarted
        daemon_reload: yes
        name: jupyter.service
