---
- hosts: 127.0.0.1
  become: true
  tasks:

    - apt: update_cache=yes

    - name: Installing jupyter-collaboration-codio
      pip:
        name: jupyter-collaboration-codio
        extra_args: -i https://test.pypi.org/simple/
        state: present
        version: 4.1.4rc0
      become: yes
      become_user: codio
      become_method: su
      become_flags: -l
      register: aptout

    - debug: var=aptout

    - name: jupyter restarted
      systemd:
        enabled: yes
        state: restarted
        daemon_reload: yes
        name: jupyter
      when: ansible_distribution_version >= "16.04"