---
- hosts: 127.0.0.1
  become: true
  tasks:

    - apt: update_cache=yes

    - name: Install Pip
      apt: name=python3-pip state=present

    - name: Installing notebook and nbgrader
      pip:
        name: jupyter-collaboration
        executable: pip3
        extra_args: --user
      become: true
      become_method: su
      become_user: codio
      become_flags: '-s /bin/sh'


    - name: Remove jupyter-server-ydoc
      pip:
        name: jupyter-server-ydoc
        executable: pip3
        state: absent
      become: true
      become_method: su
      become_user: codio
      become_flags: '-s /bin/sh'

    - name: Install jupyter-server-ydoc-codio
      pip:
        extra_args: -i https://test.pypi.org/simple/
        name: jupyter-server-ydoc-codio
        executable: pip3
        state: present
        extra_args: --user
      become: true
      become_method: su
      become_user: codio
      become_flags: '-s /bin/sh'

    - name: jupyter restarted
      systemd:
        enabled: yes
        state: restarted
        daemon_reload: yes
        name: jupyter
      when: ansible_distribution_version >= "16.04"