---
- hosts: 127.0.0.1
  become: true
  tasks:
    - name: Install Python
      apt:
        pkg:
        - python
        - python-dev
        - python-pip
        state: present
        update_cache: true
      when: ansible_facts['distribution_major_version'] | int < 22

    - name: Install Python
      apt:
        pkg:
        - python3
        - python3-dev
        - python3-pip
        state: present
        update_cache: true
      when: ansible_facts['distribution_major_version'] | int >= 22

    - name: Install mysql-connector-python
      become_user: codio
      pip:
        name: mysql-connector-python==8.0.6

    - name: Creates directory
      become_user: codio
      file:
        path: /home/codio/workspace/.guides/scripts
        state: directory

    - copy: src=helper_mysql.py dest=/home/codio/workspace/.guides/scripts/helper_mysql.py mode=a+wx
      become_user: codio
