---
- hosts: 127.0.0.1
  become: true
  tasks:
    - apt: name=python3 state=present
    - apt: name=python3-dev state=present
    - apt: name=python3-pip state=present

    - name: Install mysql-connector-python
      become_user: codio
      pip:
        name: mysql-connector-python

    - name: Creates directory
      file:
        path: /home/codio/workspace/.guides/scripts
        state: directory

    - copy: src=helper_mysql.py dest=/home/codio/workspace/.guides/scripts/helper_mysql.py mode=a+wx
