---
- hosts: 127.0.0.1
  become: yes
  become_user: root
  tasks:
    - name: install python for ubuntu < 22
      apt:
        pkg:
          - python
          - python-dev
          - python-pip
        state: present
        update_cache: true
      when: ansible_facts['distribution_major_version'] | int < 22
    - name: install python-language-server for ubuntu < 22
      pip: name=python-language-server version=0.4.2
      when: ansible_facts['distribution_major_version'] | int < 22

    - name: install python3 for ubuntu >= 22
      apt:
        pkg:
          - python3
          - python3-dev
          - python3-pip
        state: present
        update_cache: true
      when: ansible_facts['distribution_major_version'] | int >= 22
    - name: install python-language-server for ubuntu >= 22
      pip: name=python-language-server version=0.36.2
      when: ansible_facts['distribution_major_version'] | int >= 22

    - name: install pycodestyle
      pip: name=pycodestyle
