---
- hosts: 127.0.0.1
  become: yes
  become_user: root
  tasks:
    - apt: name=python3 state=present
    - apt: name=python3-dev state=present
    - apt: name=python3-pip state=present
    - pip: name=python-language-server version=0.36.2

