---
- hosts: 127.0.0.1
  become: yes
  become_user: root
  tasks:
    - apt_repository:
        repo: 'ppa:openjdk-r/ppa' 
        update_cache: yes

    - apt: name=openjdk-8-jdk state=latest
    - name: Update alternatives
      become: yes
      shell: update-java-alternatives -s java-1.8.0-openjdk-amd64
