---
- hosts: 127.0.0.1
  sudo: true
  tasks:
    - name: ensure zulu apt repository key is present
      apt_key:
        id=0xB1998361219BD9C9
        keyserver=hkp://keyserver.ubuntu.com:80
        state=present
      sudo: yes

    - name: ensure the zulu apt repository is present
      apt_repository:
        repo='deb http://repos.azulsystems.com/ubuntu stable main'
        update_cache=yes
        state=present
      sudo: yes

    - apt: name=zulu-11 state=latest

    - name: correct java version selected
      alternatives:
        name: java
        path: /usr/lib/jvm/zulu-11-amd64/bin/java