---
- hosts: 127.0.0.1
  become: true
  tasks:
    - name: Add nodesource repository
      shell: curl -sL https://deb.nodesource.com/setup_10.x | bash -

    - apt: update_cache=yes
    - apt: name=nodejs state=present
    - apt: name=build-essential state=present

    - name: PencilCode checkout
      become: yes
      become_user: codio
      git:
        repo: 'https://github.com/codio/pencilcode.git'
        dest: /home/codio/pencilcode
        update: yes
        force: yes
        version: 12466_localhost

    - copy: src=conf.json dest=/home/codio/pencilcode/server/config/development.json
      become_user: codio
    - copy: src=scripts/pencilcode-build.sh dest=/home/codio/pencilcode/pencilcode-build.sh mode=0777
      become_user: codio

    - name: Pencilcode build
      become_user: codio
      shell: sh pencilcode-build.sh
      args:
        chdir: /home/codio/pencilcode

    - copy: src=systemd/pencilcode-server.service dest=/etc/systemd/system/pencilcode-server.service

    - service: name=pencilcode-server state=restarted enabled=true