---
- hosts: 127.0.0.1
  become: true
  tasks:
    - name: Add nodesource repository
      shell: curl -sL https://deb.nodesource.com/setup_10.x | bash -

    - name: Add APT key
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: Add APT repository
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present

    - apt: update_cache=yes
    - apt: name=nodejs state=present
    - apt: name=build-essential state=present
    - apt: name=yarn state=present

    - name: PencilCode checkout
      become: yes
      become_user: codio
      git:
        repo: 'https://github.com/codio/pencilcode.git'
        dest: /home/codio/workspace
        update: yes
        force: yes
        version: master