---
- hosts: 127.0.0.1
  become: yes
  become_user: root
  tasks:
    - name: Install vscode
      apt:
        deb: https://global.codio.com/utils/code-server_4.95.2_amd64.deb

    - name: Create a systemd override
      file:
        path: /etc/systemd/system/code-server@.service.d/
        state: directory
        mode: "0755"

    - name: Copy  override
      copy:
        src: override.conf
        dest: /etc/systemd/system/code-server@.service.d/

    - name: Enable and start vscode
      systemd:
        name: "code-server@codio.service"
        daemon_reload: yes
        state: started
        enabled: yes
