---
- hosts: 127.0.0.1
  become: yes
  become_user: root
  tasks:
    - apt: name=python3 state=present
    - apt: name=python3-dev state=present
    - apt: name=python3-pip state=present
    - apt: name=python3-setuptools state=present
    - apt: name=python3-numpy state=present
    - apt: name=python3-scipy state=present
    - apt: name=python3-tk state=present
    - apt: name=ipython3 state=present
    - apt: name=build-essential state=present
