---
- hosts: 127.0.0.1
  sudo: true
  tasks:
    - apt: name=ca-certificates state=latest
    - apt: name=apt-transport-https state=present
    - name: Add apt key for nodesource
      become: yes
      shell: curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
    - name: Add repo for nodesource
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main' 
        update_cache: yes

    - name: Install nodejs
      apt: name=nodejs state=latest
      