---
- hosts: 127.0.0.1
  sudo: true
  tasks:
    - apt: name=ca-certificates state=latest
    - apt: name=apt-transport-https state=present
    - name: add repo
      become: yes
      shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

    - name: Install nodejs
      apt: name=nodejs state=latest
      