---
- hosts: 127.0.0.1
  become: true
  become_user: root
  tasks:
    - apt: name=ca-certificates state=latest
    - apt: name=apt-transport-https state=present
    
    - name: add repo
      shell: curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -

    - name: Install nodejs
      apt: name=nodejs state=latest
