---
- hosts: 127.0.0.1
  become: true
  become_user: root
  tasks:
    - name: Ensure Eclipse Adoptium apt repository key is present
      apt_key:
        url: https://packages.adoptium.net/artifactory/api/gpg/key/public
        state: present

    - name: Ensure Eclipse Adoptium apt repository is present
      apt_repository:
        repo: 'deb https://packages.adoptium.net/artifactory/deb {{ ansible_distribution_release }} main'
        filename: openjdk_adoptium
        update_cache: yes
        state: present

    - apt:
        name: temurin-8-jdk
        state: latest

    - name: Select the version of Java as a default
      alternatives:
        name: java
        path: /usr/lib/jvm/temurin-8-jdk-amd64/bin/java
