---
- hosts: 127.0.0.1
  become: yes
  become_user: root
  tasks:
    - apt: name=apache2 state=present
    - name: Ensure apache2 is running
      service:
        name=apache2
        state=started
    - apache2_module: state=present name=rewrite
    - action: copy src=ports.conf dest=/etc/apache2/ports.conf 
      notify: restart apache2
    - name: Vhost update
      action: copy
        src=vhost.conf
        dest=/etc/apache2/sites-available/000-default.conf
      notify: restart apache2
  handlers:
    - name: restart apache2
      service:
        name=apache2
        state=restarted